### ISSUE TITLE
getStatusAttribute needs to be cast to string

### ISSUE THREAD

**Issue by JacobBennett** [makeabledk/laravel-eloquent-status#5]
If you are calling 

```
public function getStatusAttribute()
{
    return ApprovalStatus::guess($this);
}
```

it will return an instance of `ApprovalStatus` but will not return the string representing the current state. When rendering this to a blade template, it is likely that it is cast to a string and works fine. However if wanting to use it outside of just presentation methods, you must be explicit about casting it to a string from within the `getStatusAttribute` like this.

```
public function getStatusAttribute()
{
    return (string) ApprovalStatus::guess($this);
}
```

This could also be done from within the `guess` method itself as I assume the original intent is to provide a string representation of the status and not an instance of the class being used to guess it.

**Comment by rasmuscnielsen** [comment]
I see your point there.

However it feels a bit better to me to return an instance from the `guess` method rather than a string. This leaves it up to the developer to decide which they prefer. Sort of like the `Approval::find()` method on eloquent.

I could imagine some cases down the line where someone may want to extend the `Status` object with more helper functions, making it handy to have the actual instance. 

In case you find yourself always casting to a string you could extend the `Status` yourself and overwrite the `guess` method or apply a `GuessesString` trait.

```php
public static function guess() 
{
    return (string) parent::guess();
}
```

Note that if you are using API resources it automatically casts to string as it implements the `JsonSerializable` interface.
